# Generated by Django 5.0.1 on 2024-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoreddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
